-- Data is generated by the project pre-render hook before shortcodes execute.
return {
  ["portfolio"] = function(args)
    local name = pandoc.utils.stringify(args[1])
    local allowed = {home=true, publications=true, news=true, outreach=true, about=true}
    if not allowed[name] then error("Unknown portfolio section: " .. name) end
    local path = quarto.project.directory .. "/_generated/" .. name .. ".html"
    local file = assert(io.open(path, "r"), "Run tools/build-content.py before rendering")
    local html = file:read("*all")
    file:close()
    return pandoc.RawBlock("html", html)
  end
}
